name: Cypress Testing SanberCode64 on Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: windows-latest  # Menjalankan di Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3  # Mengambil kode dari repo

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Sesuaikan dengan versi Node.js proyekmu

      - name: Install Dependencies
        run: npm install  # Install semua dependency proyek

      - name: Run Cypress Tests
        run: npx cypress run  # Menjalankan Cypress secara headless (tanpa UI)

      - name: Upload Cypress Screenshots & Videos (jika ada error)
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-artifacts
          path: |
            cypress/screenshots
            cypress/videos